ChatServerPlayground/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path

from personal.views import (
    home_screen_view,
)

from  account.views import (
    register_view,
    login_view,
    logout_view,
    account_search_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name='home'),
    path('register/', register_view, name="register"),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('account/', include('account.urls', namespace='account')),
    path('friend/', include('friend.urls', namespace='friend')),
    path('search/', account_search_view, name='search'),
    path('chat/', include('chat.urls', namespace='chat')),
     # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
]
if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path

from account.views import (
    account_view,
    edit_account_view,
    crop_image,
)

app_name = "account"

urlpatterns = [
    path('<user_id>/', account_view, name="view"),
    path('<user_id>/edit/', edit_account_view, name="edit"),
    path('<user_id>/edit/cropImage', crop_image, name="crop_image"),
]

chat/urls.py
from django.urls import path

from chat.views import(
	private_chat_room_view,
	create_or_return_private_chat,
)

app_name = 'chat'

urlpatterns = [
	path('', private_chat_room_view, name='private-chat-room'),
	path('create_or_return_private_chat/', create_or_return_private_chat, name='create-or-return-private-chat'),
]

friend/urls.py
from django.urls import path
from friend.views import (
    send_friend_request,
    friend_requests,
    accept_friend_request,
    remove_friend,
    decline_friend_request,
    cancel_friend_request,
    friend_list_view,
)

app_name = "friend"

urlpatterns = [
    path('list/<user_id>/', friend_list_view, name="list"),
    path('friend_remove/', remove_friend, name="remove-friend"),
    path('friend_request/', send_friend_request, name="friend-request"),
    path('friend_request_cancel/', cancel_friend_request, name="friend-request-cancel"),
    path('friend_request/<user_id>/', friend_requests, name="friend-requests"),
    path('accept_friend_request/<friend_request_id>/', accept_friend_request, name="friend-request-accept"),
    path('decline_friend_request/<friend_request_id>/', decline_friend_request, name="friend-request-decline"),
]

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.core.files.storage import FileSystemStorage
from django.conf import settings
import os
from django.db.models.signals import post_save
from django.dispatch import receiver
from friend.models import FriendList

# Create your models here.

class MyAccountManager(BaseUserManager):

    # create a new user
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError("Users must have an email address.")
        if not username:
            raise ValueError("Users must have a username.")
        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    # create a new superuser
    def create_superuser(self, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

def get_profile_image_filepath(self, filename):
    return f'profile_images/{self.pk}/{"profile_image.png"}'

def get_default_profile_image():
    return "MoreImages/logo_1080_1080.png"

class Account(AbstractBaseUser):
    # email is required
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    #-----------------------------------------------------
    username = models.CharField(max_length=30, unique=True)
    date_joined = models.DateTimeField(verbose_name="date joined", auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="date joined", auto_now=True)
    # these fields are also required when extending AbstractBaseUser
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    #-----------------------------------------------------
    profile_image = models.ImageField(max_length=255, upload_to=get_profile_image_filepath, null=True, blank=True, default=get_default_profile_image)
    hide_email = models.BooleanField(default=True)

    objects = MyAccountManager()
    # users must have and email and username
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username

    def get_profile_image_filename(self):
        return str(self.profile_image)[str(self.profile_image).index(f'profile_images/{self.pk}/'):]

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True
# Whenever a change is made to an account we want to save something (in this case a friends list)
@receiver(post_save, sender=Account)
def user_save(sender, instance, **kwargs):
    FriendList.objects.get_or_create(user=instance)

account/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login, authenticate, logout
from account.forms import RegistrationForm, AccountAuthenticationForm, AccountUpdateForm
from django.conf import settings
from django.core.files.storage import default_storage
from django.core.files.storage import FileSystemStorage
import os
import cv2
import json
import base64
#import requests
from django.core import files
from account.models import Account
from friend.friend_request_status import FriendRequestStatus
from friend.utils import get_friend_request_or_false
from friend.models import FriendList, FriendRequest

TEMP_PROFILE_IMAGE_NAME = "temp_profile_image.png"

# Create your views here.
def get_redirect_if_exists(request):
    redirect = None
    if request.GET:
        if request.GET.get("next"):
            redirect = str(request.GET.get("next"))
    return redirect

def register_view(request, *args, **kwargs):
    user = request.user
    if user.is_authenticated:
        return HttpResponse(f"You are already authenticated as {user.email}.")
    context = {}

    if request.POST:
        form = RegistrationForm(request.POST)
        if form.is_valid():
            # create the account
            form.save()
            # login the account
            email = form.cleaned_data.get('email').lower()
            raw_password = form.cleaned_data.get('password1')
            account = authenticate(email=email, password=raw_password)
            login(request, account)
            destination = get_redirect_if_exists(request)
            if destination: # if destination is not None
                return redirect(destination)
            else:
                return redirect("home")
        else:
            context['registration_form'] = form
    return render(request, 'register.html', context)

def logout_view(request):
    logout(request)
    return redirect ("home")


def login_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if user.is_authenticated:
        return redirect("home")
    
    if request.POST:
        form = AccountAuthenticationForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password)
            if user:
                login(request, user)
                destination = get_redirect_if_exists(request)
                if destination:
                    return redirect(destination)
                return redirect("home")
        else:
            # sends the errors back to the view if they occur
            context['login_form'] = form

    return render(request, "login.html", context)

def account_view(request, *args, **kwargs):
	"""
	- Logic here is:
		is_self (boolean)
			is_friend (boolean)
				-1: NO_REQUEST_SENT
				0: THEM_SENT_TO_YOU
				1: YOU_SENT_TO_THEM
	"""
	context = {}
	user_id = kwargs.get("user_id")
	try:
		account = Account.objects.get(pk=user_id)
	except:
		return HttpResponse("Something went wrong.")
	if account:
		context['id'] = account.id
		context['username'] = account.username
		context['email'] = account.email
		context['profile_image'] = account.profile_image.url
		context['hide_email'] = account.hide_email

		try:
			friend_list = FriendList.objects.get(user=account)
		except FriendList.DoesNotExist:
			friend_list = FriendList(user=account)
			friend_list.save()
		friends = friend_list.friends.all()
		context['friends'] = friends
	
		# Define template variables
		is_self = True
		is_friend = False
		request_sent = FriendRequestStatus.NO_REQUEST_SENT.value # range: ENUM -> friend/friend_request_status.FriendRequestStatus
		friend_requests = None
		user = request.user
		if user.is_authenticated and user != account:
			is_self = False
			if friends.filter(pk=user.id):
				is_friend = True
			else:
				is_friend = False
				# CASE1: Request has been sent from THEM to YOU: FriendRequestStatus.THEM_SENT_TO_YOU
				if get_friend_request_or_false(sender=account, receiver=user) != False:
					request_sent = FriendRequestStatus.THEM_SENT_TO_YOU.value
					context['pending_friend_request_id'] = get_friend_request_or_false(sender=account, receiver=user).id
				# CASE2: Request has been sent from YOU to THEM: FriendRequestStatus.YOU_SENT_TO_THEM
				elif get_friend_request_or_false(sender=user, receiver=account) != False:
					request_sent = FriendRequestStatus.YOU_SENT_TO_THEM.value
				# CASE3: No request sent from YOU or THEM: FriendRequestStatus.NO_REQUEST_SENT
				else:
					request_sent = FriendRequestStatus.NO_REQUEST_SENT.value
		
		elif not user.is_authenticated:
			is_self = False
		else:
			try:
				friend_requests = FriendRequest.objects.filter(receiver=user, is_active=True)
			except:
				pass
			
		# Set the template variables to the values
		context['is_self'] = is_self
		context['is_friend'] = is_friend
		context['request_sent'] = request_sent
		context['friend_requests'] = friend_requests
		context['BASE_URL'] = settings.BASE_DIR
		return render(request, "account.html", context)

def account_search_view(request, *args, **kwargs):
	user = request.user
	context = {}
	if request.method == 'GET':
		search_query = request.GET.get("q")
		if len(search_query) > 0:
			search_results = Account.objects.filter(email__icontains=search_query).filter(username__icontains=search_query).distinct()
			accounts = [] # [(account1, True), (account2, False),....]
			if user.is_authenticated:
				# get the authenticated users friend list
				auth_user_friend_list = FriendList.objects.get(user=user)
				for account in search_results:
					accounts.append((account, auth_user_friend_list.is_mutual_friend(account)))
				context['accounts'] = accounts
			else:
				for account in search_results:
					accounts.append((account, False))
				context['accounts'] = accounts

	return render(request, 'search_results.html', context)

def edit_account_view(request, *args, **kwargs):
    if not request.user.is_authenticated:
        return redirect("login")
    user_id = kwargs.get("user_id")
    try:
        account = Account.objects.get(pk=user_id)
    except Account.DoesNotExist:
        raise HttpResponse("Something went wrong.")
    if account.pk != request.user.pk:
        return HttpResponse("You cannot edit a profile that is not your own.")
    context = {}
    if request.POST:
        form = AccountUpdateForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("account:view", user_id=account.pk)
        else:
            form = AccountUpdateForm(request.POST, instance=request.user,
            initial = {
                "id": account.pk,
                "email": account.email,
                "username": account.username,
                "profile_image": account.profile_image,
                "hide_email": account.hide_email
            })
            context['form'] = form
    else:
        form = AccountUpdateForm(
            initial = {
                "id": account.pk,
                "email": account.email,
                "username": account.username,
                "profile_image": account.profile_image,
                "hide_email": account.hide_email
            })
        context['form'] = form
    context['DATA_UPLOAD_MAX_MEMORY_SIZE'] = settings.DATA_UPLOAD_MAX_MEMORY_SIZE
    return render(request, 'update_account.html', context)

def save_temp_profile_image_from_base64String(imageString, user):
	INCORRECT_PADDING_EXCEPTION = "Incorrect padding"
	try:
		if not os.path.exists(settings.TEMP):
			os.mkdir(settings.TEMP)
		if not os.path.exists(settings.TEMP + "/" + str(user.pk)):
			os.mkdir(settings.TEMP + "/" + str(user.pk))
		url = os.path.join(settings.TEMP + "/" + str(user.pk),TEMP_PROFILE_IMAGE_NAME)
		storage = FileSystemStorage(location=url)
		image = base64.b64decode(imageString)
		with storage.open('', 'wb+') as destination:
			destination.write(image)
			destination.close()
		return url
	except Exception as e:
		print("exception: " + str(e))
		# workaround for an issue I found
		if str(e) == INCORRECT_PADDING_EXCEPTION:
			imageString += "=" * ((4 - len(imageString) % 4) % 4)
			return save_temp_profile_image_from_base64String(imageString, user)
	return None


def crop_image(request, *args, **kwargs):
	payload = {}
	user = request.user
	if request.POST and user.is_authenticated:
		try:
			imageString = request.POST.get("image")
			url = save_temp_profile_image_from_base64String(imageString, user)
			img = cv2.imread(url)

			cropX = int(float(str(request.POST.get("cropX"))))
			cropY = int(float(str(request.POST.get("cropY"))))
			cropWidth = int(float(str(request.POST.get("cropWidth"))))
			cropHeight = int(float(str(request.POST.get("cropHeight"))))
			if cropX < 0:
				cropX = 0
			if cropY < 0: # There is a bug with cropperjs. y can be negative.
				cropY = 0
			crop_img = img[cropY:cropY+cropHeight, cropX:cropX+cropWidth]

			cv2.imwrite(url, crop_img)

			# delete the old image
			user.profile_image.delete()

			# Save the cropped image to user model
			user.profile_image.save("profile_image.png", files.File(open(url, 'rb')))
			user.save()

			payload['result'] = "success"
			payload['cropped_profile_image'] = user.profile_image.url

			# delete temp file
			os.remove(url)
			
		except Exception as e:
			print("exception: " + str(e))
			payload['result'] = "error"
			payload['exception'] = str(e)
	return HttpResponse(json.dumps(payload), content_type="application/json")

account/templates/account.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style type="text/css">
	.image-container{
		max-width: 250px;
		height: auto;
	}
	.field-heading{
		color: var(--secondary-text-color);
	}
	.icon-container:hover {
		opacity: 0.3;
		cursor: pointer;
	}
	.friends-icon{
		color: #4287f5;
		font-size: 40px;
	}
	.person-add-icon{
		color: #4287f5;
		font-size: 40px;
	}
	.friend-text{
		font-weight: 500;
		color: black;
	}
	.friends-btn{
		background-color: #cccccc;
		border-color: #cccccc;
		color: #000;
		font-weight: 500;
	}
	.friends-btn:hover {
		background-color: #bfbfbf;
		border-color: #bfbfbf;
	}
	.dropdown-toggle::after { 
		content: none; 
	}
	.card{
		border-radius: 12px;
	}
	.material-icons{
		font-size: 30px;
	}
	.material-icons:hover{
		cursor: pointer;
	}
	.confirm-friend-request{
		color: green;
	}
	.confirm-friend-request:hover {
		opacity: 0.3;
	}
	.decline-friend-request:hover {
		opacity: 0.3;
	}
	.decline-friend-request{
		color: red;
	}
	.message-btn-text{
		font-weight: 500;
	}
</style>

<div class="container-fluid">
	<div class="d-flex flex-row justify-content-center flex-wrap align-items-start">

		<div class="card profile-card m-2">
		  <div class="card-body">
		  	<div class="d-flex flex-column justify-content-center p-4">
		  		<div class="image-container mx-auto mb-4">
		  			<img class="d-block border border-dark rounded-circle img-fluid mx-auto profile-image" alt="logo" id="id_profile_image" src="{{profile_image}}">
		  		</div>
		  		<p class="mt-4 mb-1 field-heading">Email</p>
		  		{%  if is_self %}
		  			<h5>{{email}}</h5>
		  		{% else %}
		  			{% if hide_email %}
			  			<h5>**********</h5>
			  		{% else %}
			  			<h5>{{email}}</h5>
			  		{% endif %}
			  	{% endif %}
		  		<p class="mt-4 mb-1 field-heading">Username</p>
		  		<h5>{{username}}</h5>

		  		<!-- If Auth user is viewing their own profile -->
		  		{% if is_self %}
		  		<a  class="mt-4 btn btn-primary" href="{% url 'account:edit' user_id=id %}">Update</a>
				<div class="d-flex flex-column mt-4">
					<a class="m-auto" href="{% url 'password_change' %}">Change password</a>
				</div>
		  		{% endif %}
		  	</div>
		  </div>
		</div>

		{% if request.user.is_authenticated %}
		<div class="d-flex flex-column mb-4">

			<!-- THEM to YOU -->
			{% if request_sent == 0 %}
			<div class="card m-2 p-4">
				<div class="d-flex flex-row align-items-center">
					<span class="friend-text align-items-center mr-2">Accept Friend Request</span>
					<span id="id_cancel_{{id}}" class="decline-friend-request material-icons p-1" onclick='triggerDeclineFriendRequest("{{pending_friend_request_id}}")'>cancel</span>
  					<span id="id_confirm_{{id}}" class="confirm-friend-request material-icons p-1" onclick='triggerAcceptFriendRequest("{{pending_friend_request_id}}")'>check</span>
				</div>
			</div>
			{% endif %}

			<div class="card m-2 px-4 pb-4">
				<!-- Cancel Friend Request / Send Friend Request / Remove Friend -->
				{% if is_friend == False and is_self == False %}
						<!-- You sent them a request -->
						{% if request_sent == 1 %}
						<div class="d-flex flex-column align-items-center pt-4">
							<button class="btn btn-danger" id="id_cancel_friend_request_btn">
								Cancel Friend Request
							</button>
						</div>
						{% endif %}
						<!-- No requests have been sent -->
						{% if request_sent == -1 %}
						<div class="d-flex flex-column align-items-center pt-4">
							<button class="btn btn-primary" id="id_send_friend_request_btn">
								Send Friend Request
							</button>
						</div>
						{% endif %}
				{% endif %}
					
					
				{% if is_friend %}
					<div class="dropdown pt-4 m-auto">
						<button class="btn btn-secondary dropdown-toggle friends-btn" type="button" id="id_friends_toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Friends
						</button>
						<div class="dropdown-menu" aria-labelledby="id_friends_toggle">
							<a class="dropdown-item" href="#" onclick="removeFriend('{{id}}', onFriendRemoved)">Unfriend</a>
						</div>
					</div>
				{% endif %}
				
				<!-- TODO -->
				<!-- Friend list link -->
		  		<div class="d-flex flex-column pt-4">
					<a href="{% url 'friend:list' user_id=id %}">
						<div class="d-flex flex-row align-items-center justify-content-center icon-container">
							<span class="material-icons mr-2 friends-icon">contact_page</span><span class="friend-text">Friends ({{friends|length}})</span>
						</div>
					</a>
				</div>

			</div>

			{% if friend_requests %}
			<div class="card m-2 px-4 pb-4">
				<!-- Friend requests -->
		  		<div class="d-flex flex-column pt-4">
					<a href="{% url 'friend:friend-requests' user_id=id%}">
						<div class="d-flex flex-row align-items-center justify-content-center icon-container">
							<span class="material-icons mr-2 person-add-icon">person_add</span><span class="friend-text">Friend Requests ({{friend_requests|length}})</span>
						</div>
					</a>
				</div>
			</div>
			{% endif %}

			{% if is_friend %}
				<div class="d-flex flex-row align-items-center btn btn-primary m-2 px-4" onclick="createOrReturnPrivateChat('{{id}}')">
					<span class="material-icons m-auto">
					message
					</span>
					<span class="message-btn-text m-auto pl-2">Message</span>
				</div>
			{% endif %}

		</div>
		{% endif %}

		
	</div>
</div>


<script type="text/javascript">

	// called from base_js.html
	//preloadImage("{{profile_image|safe}}", 'id_profile_image')

	function onFriendRequestSent(){
		location.reload();
	}

	function onFriendRequestCancelled(){
		location.reload();
	}

	function onFriendRemoved(){
		location.reload();
	}

	function onFriendRequestAccepted(){
		location.reload();
	}

	function onFriendRequestDeclined(){
		location.reload();
	}


	var sendFriendRequestBtn = document.getElementById("id_send_friend_request_btn")
	if (sendFriendRequestBtn != null){
		sendFriendRequestBtn.addEventListener("click", function(){
			sendFriendRequest("{{id}}", onFriendRequestSent)
		})
	}

	var cancelFriendRequestBtn = document.getElementById("id_cancel_friend_request_btn")
	if(cancelFriendRequestBtn != null){
		cancelFriendRequestBtn.addEventListener("click", function(){
			cancelFriendRequest("{{id}}", onFriendRequestCancelled)
		})
	}

	var removeFriendBtn = document.getElementById("id_unfriend_btn")
	if (removeFriendBtn != null){
		removeFriendBtn.addEventListener("click", function(){
			removeFriend("{{id}}", onFriendRemoved)
		})
	}

	function triggerAcceptFriendRequest(friend_request_id){
		acceptFriendRequest(friend_request_id, onFriendRequestAccepted)
	}

	function triggerDeclineFriendRequest(friend_request_id){
		declineFriendRequest(friend_request_id, onFriendRequestDeclined)
	}
</script>

{% include 'snippets/send_friend_request.html' %}
{% include 'snippets/accept_friend_request.html' %}
{% include 'snippets/decline_friend_request.html' %}
{% include 'snippets/cancel_friend_request.html' %}
{% include 'snippets/remove_friend.html' %}
{% include 'snippets/create_or_return_private_chat.html' %}



{% endblock content %}

account/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<style type="text/css">

  .card-signin {
	  width: 100%;
	  max-width: 400px;
	  padding: 15px;
	  margin: auto;
  }
  
  .form-signin input[type="email"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .form-signin input[type="password"] {
    margin-bottom: -1px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
  }


</style>

<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="card card-signin">
		  <div class="card-body">
		    <form class="form-signin" method="post">{% csrf_token %}
				<div class="d-flex flex-column pb-3">
				</div>
				<input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>

				<input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
                <br>

				{% for field in login_form %}
				<p>
				{% for error in field.errors %}
				<p style="color: red">{{ error }}</p>
				{% endfor %}
				</p>
				{% endfor %}
				{% if login_form.non_field_errors %}
				<div style="color: red">
				<p>{{login_form.non_field_errors}}</p>
				</div>

				{% endif %}

				<button class="btn btn-lg btn-primary btn-block" type="submit">Log in</button>
				</form>

				<div class="d-flex flex-column my-4">
					<a class="m-auto" href="{% url 'password_reset' %}">Reset password</a>
				</div>
		  </div>
		</div>
		
	</div>
</div>






{% endblock content %}

account/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<style type="text/css">

  .card-signin {
	  width: 100%;
	  max-width: 400px;
	  padding: 15px;
	  margin: auto;
  }
  
  .form-signin input[type="email"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .form-signin input[type="text"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .form-signin input[type="password"] {
    margin-bottom: 10px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
  }


</style>

<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="card card-signin">
		  <div class="card-body">
		    <form class="form-signin" method="post">{% csrf_token %}
				<div class="d-flex flex-column pb-3">
				</div>
				<input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>

				<input type="text" name="username" id="inputUsername" class="form-control" placeholder="Username" required>

				<input type="password" name="password1" id="inputPassword1" class="form-control" placeholder="Password" required>

				<input type="password" name="password2" id="inputPassword2" class="form-control" placeholder="Confirm password" required>
                <br>

				{% for field in registration_form %}
				<p>
				{% for error in field.errors %}
				<p style="color: red">{{ error }}</p>
				{% endfor %}
				</p>
				{% endfor %}
				{% if registration_form.non_field_errors %}
				<div style="color: red">
					<p>{{registration_form.non_field_errors}}</p>
				</div>

				{% endif %}

				<button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>

				</form>
		  </div>
		</div>
		
	</div>
</div>






{% endblock content %}

account/templates/search_results.html
<!-- This is basically exactly the same as friend_list.html -->

{% extends 'base.html' %}
{% load static %}

{% block content %}


<style type="text/css">
	.profile-image{
		max-height: 100px;
		max-width: 100px;
	}
	.profile-image{
		border-radius: 12px;
	}
	.card{
		border-radius: 12px;
	}
	.friends-text{
		color: #000;
		font-weight: 500;
	}
	.friends-text-container{
		border: 1px solid #cccccc;
		border-radius: 12px;
	}
	.friends-btn:hover {
		background-color: #bfbfbf;
		border-color: #bfbfbf;
	}
	.dropdown-toggle::after { 
		content: none; 
	}
	.profile-link{
		color: #000;
	}
	.checkmark-icon{
		color: green;
	}
	.cancel-icon{
		color: red;
	}
</style>

<div class="container">
	<div class="card p-2">

		{% if accounts %}
		<div class="d-flex flex-row flex-wrap">
		{% for account in accounts %}
		<div class="card flex-row flex-grow-1 p-2 mx-2 my-2 align-items-center">
			<a class="profile-link" href="{% url 'account:view' user_id=account.0.id %}">
				<div class="card-image m-2">
					<img class="img-fluid profile-image" src="{{account.0.profile_image.url}}" alt="">
				</div>
			</a>
			<a class="profile-link" href="{% url 'account:view' user_id=account.0.id %}">
				<div class="card-center px-2">
					<h4 class="card-title">{{account.0.username}}</h4>
					{% if account.1 %}
					<p class="card-text"><a href="#" onclick="createOrReturnPrivateChat('{{account.0.id}}')">Send a Message</a></p>
					{% endif %}
					
				</div>
			</a>
			<div class="d-flex flex-row card-right flex-grow-1 justify-content-end mx-2">
				{% if account.1 %}
					<div class="d-flex flex-row friends-text-container p-3">
						<p class="friends-text m-auto">
							Friends 
						</p>
						<span class="material-icons checkmark-icon m-auto pl-2">
						check_circle_outline
						</span>
					</div>
				{% else %}
					{% if account.0 !=  request.user %}
						<div class="d-flex flex-row friends-text-container p-3">
							<p class="friends-text m-auto">
								Not Friends 
							</p>
							<span class="material-icons cancel-icon m-auto pl-2">cancel</span>
						</div>
					{% endif %}
				{% endif %}
				{% if account.0 == request.user %}
					<div class="d-flex flex-row friends-text-container p-3">
						<p class="friends-text m-auto">
							This is you 
						</p>
						<span class="material-icons m-auto pl-2">
						person_pin
						</span>
					</div>
				{% endif %}
			</div>
		</div>
		{% if forloop.counter|divisibleby:2 %}
		</div><div class="d-flex flex-row flex-wrap">
		{% endif %}
		
		{% endfor %}
		
		{% else %} <!-- If no friends -->
		<div class="d-flex flex-row flex-grow-1 justify-content-center align-items-center p-4">
			<p>No results</p>
		</div>
		{% endif %}
		</div>
	</div>
	
</div>


{%  include 'snippets/create_or_return_private_chat.html' %}

{% endblock content %}